"""
Adaptateurs de la phase 2 -- catégorie 1.

Chaque nature de fichier (`kind`) devient un ou plusieurs `DocCandidate`,
objet intermédiaire local à cat1. Les candidats retenus après filtrage,
déduplication et quotas sont convertis en `DocumentDraft` (objet commun) par
`build_corpus.py` : l'assembleur et le schéma de sortie restent inchangés,
conformément au principe d'extension du projet.

Granularité choisie, par nature :

  docs        1 fichier = 1 document. Une page de tutoriel est déjà une
              unité de sens.
  code        1 fichier = 1 document.
  interfaces  1 PAQUET = 1 document. Un `.msg` isolé fait 30 tokens et n'a
              aucun sens hors contexte ; regroupés par paquet, ils forment
              le vocabulaire de commande complet d'un domaine
              (`geometry_msgs`, `nav2_msgs`...).
  notebooks   1 notebook = 1 document, cellules markdown + code seulement.
              Les sorties d'exécution sont jetées : elles représentent
              l'essentiel du poids des .ipynb et n'apportent aucun texte
              exploitable.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

# Seuils de qualité. Un fichier trop court est du bruit de structure
# (page d'index, redirection) ; il ferait du volume sans contenu.
MIN_CHARS_DOC = 400
MIN_CHARS_CODE = 300
MIN_CHARS_INTERFACE = 200

# Fichiers générés automatiquement : leur contenu est répétitif et
# n'apprend rien qu'on ne trouve mieux ailleurs.
_GENERATED_MARKERS = (
    "do not edit", "do not modify", "automatically generated",
    "autogenerated", "auto-generated", "@generated", "generated by",
)

_CODE_EXT = {".py", ".cpp", ".hpp", ".h", ".c", ".cc"}
_DOC_EXT = {".rst", ".md", ".markdown"}
_INTERFACE_EXT = {".msg", ".srv", ".action"}

# Taille maximale d'un document du corpus, en caractères (~7 k tokens).
# Sans plafond, un seul fichier peut confisquer le quota de sa source : la
# référence XML de MuJoCo pesait 87 000 tokens, soit 5,7 % de tout cat1 et
# les trois quarts du budget de sa source -- 4 documents MuJoCo retenus au
# lieu de plusieurs dizaines. Un document trop long est de toute façon
# redécoupé arbitrairement à l'entraînement : autant le couper ici, à des
# frontières qui ont un sens.
MAX_DOC_CHARS = 28_000


@dataclass
class DocCandidate:
    doc_id: str            # identifiant stable, entre dans l'id du corpus
    source_id: str
    family: str
    kind: str
    rel_path: str          # chemin dans la source, pour la traçabilité
    group: str             # sous-arbre d'origine, utilisé pour la diversité
    text: str
    n_tokens: int = 0
    flags: Dict[str, str] = field(default_factory=dict)


# --------------------------------------------------------------------------
# Nettoyage
# --------------------------------------------------------------------------

# Directives Sphinx sans contenu textuel utile : on retire la directive ET
# son corps indenté. Les directives à contenu (note, warning, code-block...)
# sont volontairement absentes de cette liste : leur texte compte.
_RST_DROP_DIRECTIVES = {
    "toctree", "image", "figure", "only", "raw", "contents", "highlight",
    "index", "meta", "redirect-from", "include", "tab-set", "tabs",
    "youtube", "graphviz", "sectionauthor", "codeauthor",
}
_RST_DIRECTIVE_LINE = re.compile(r"^([ \t]*)\.\.[ \t]+([A-Za-z0-9_-]+)::")
_RST_ROLE = re.compile(r":[a-z:]+:`([^`]+)`")
_RST_ANCHOR = re.compile(r"^[ \t]*\.\.[ \t]+_[^:]+:[ \t]*$\n?", re.MULTILINE)
_RST_ORPHAN = re.compile(r"^[ \t]*:orphan:[ \t]*$\n?", re.MULTILINE)
_MD_FRONTMATTER = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)
_MD_BADGE = re.compile(r"^\[!\[[^\]]*\]\([^)]*\)\]\([^)]*\)[ \t]*$\n?", re.MULTILINE)
_HTML_COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)
_BLANKS = re.compile(r"\n{3,}")


def _drop_rst_directives(text: str) -> str:
    """
    Retire les directives sans contenu utile AVEC leur corps.

    Un simple retrait de la ligne de directive laissait ses options
    orphelines dans le corpus (`:depth: 2`, `:local:` flottant sous un
    titre). On consomme donc toute ligne plus indentée que la directive,
    ce qui est exactement sa portée en reStructuredText.
    """
    lines = text.split("\n")
    out: List[str] = []
    i = 0
    while i < len(lines):
        m = _RST_DIRECTIVE_LINE.match(lines[i])
        if m and m.group(2).lower() in _RST_DROP_DIRECTIVES:
            indent = len(m.group(1).expandtabs())
            i += 1
            consumed = False
            while i < len(lines):
                line = lines[i]
                if not line.strip():
                    i += 1
                    consumed = True
                    continue
                if len(line.expandtabs()) - len(line.expandtabs().lstrip()) > indent:
                    i += 1
                    consumed = True
                    continue
                break
            if consumed:
                out.append("")     # ne pas souder les deux paragraphes voisins
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def clean_rst(text: str) -> str:
    text = _RST_ORPHAN.sub("", text)
    text = _RST_ANCHOR.sub("", text)
    text = _drop_rst_directives(text)
    # Les rôles Sphinx (:doc:`ceci`, :class:`Cela`) sont réduits à leur
    # libellé : le balisage n'apprend rien, le mot si.
    text = _RST_ROLE.sub(r"\1", text)
    return _BLANKS.sub("\n\n", text).strip()


def clean_md(text: str) -> str:
    text = _MD_FRONTMATTER.sub("", text)
    text = _HTML_COMMENT.sub("", text)
    text = _MD_BADGE.sub("", text)
    return _BLANKS.sub("\n\n", text).strip()


def clean_text_file(path: Path, text: str) -> str:
    if path.suffix.lower() == ".rst":
        return clean_rst(text)
    if path.suffix.lower() in (".md", ".markdown"):
        return clean_md(text)
    return _BLANKS.sub("\n\n", text).strip()


def looks_generated(text: str) -> bool:
    head = text[:1500].lower()
    return any(m in head for m in _GENERATED_MARKERS)


def _read(path: Path) -> Optional[str]:
    try:
        return path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return None


# --------------------------------------------------------------------------
# Découpage des documents trop longs
# --------------------------------------------------------------------------

# Titre reStructuredText : une ligne de texte suivie d'une ligne de
# soulignement de même nature (===, ---, ~~~...).
_RST_SECTION = re.compile(r"^\S.*\n[=\-~^\"'`#*+]{3,}[ \t]*$", re.MULTILINE)
_MD_HEADING = re.compile(r"^#{1,3}[ \t]+\S.*$", re.MULTILINE)
_PY_TOPLEVEL = re.compile(r"^(?:def |class |@\w)", re.MULTILINE)
_CXX_TOPLEVEL = re.compile(r"^(?:[A-Za-z_][\w:<>,& *]*\s+)?[A-Za-z_]\w*::"
                           r"|^(?:class|struct|namespace)\s+\w", re.MULTILINE)
_PARAGRAPH = re.compile(r"\n\s*\n")


def _boundaries(text: str, ext: str):
    """Positions de début des sections naturelles du document."""
    if ext == ".rst":
        pattern = _RST_SECTION
    elif ext in (".md", ".markdown"):
        pattern = _MD_HEADING
    elif ext == ".py":
        pattern = _PY_TOPLEVEL
    elif ext in (".cpp", ".hpp", ".h", ".c", ".cc"):
        pattern = _CXX_TOPLEVEL
    else:
        pattern = _PARAGRAPH
    found = [m.start() for m in pattern.finditer(text)]
    if len(found) < 2:
        found = [m.start() for m in _PARAGRAPH.finditer(text)]
    return sorted({0, *found})


def _hard_split(segment: str, max_chars: int):
    """Dernier recours : découpe aux paragraphes une section déjà trop longue."""
    if len(segment) <= max_chars:
        return [segment]
    parts, current = [], ""
    for para in _PARAGRAPH.split(segment):
        candidate = f"{current}\n\n{para}" if current else para
        if len(candidate) > max_chars and current:
            parts.append(current)
            current = para
        else:
            current = candidate
    if current:
        parts.append(current)
    return parts


def split_document(text: str, ext: str, max_chars: int = MAX_DOC_CHARS):
    """
    Découpe un document trop long à ses frontières de sections.

    Aucun texte n'est ajouté ni reformulé : les parties concaténées
    redonnent exactement le document d'origine. Le rang de la partie est
    porté par les métadonnées de l'enregistrement, pas par le texte.
    """
    if len(text) <= max_chars:
        return [text]

    bounds = _boundaries(text, ext)
    segments = [text[a:b] for a, b in zip(bounds, list(bounds[1:]) + [len(text)])]

    parts: List[str] = []
    current = ""
    for seg in segments:
        if len(seg) > max_chars:
            if current:
                parts.append(current)
                current = ""
            parts.extend(_hard_split(seg, max_chars))
            continue
        if len(current) + len(seg) > max_chars and current:
            parts.append(current)
            current = seg
        else:
            current += seg
    if current:
        parts.append(current)
    return [p.strip() for p in parts if p.strip()]


def _group_of(rel: Path) -> str:
    """Sous-arbre de premier niveau -- sert à répartir la sélection."""
    parts = rel.parts
    if len(parts) <= 1:
        return "(racine)"
    # source/Tutorials/Beginner/... -> on descend d'un cran quand le
    # premier niveau est un simple conteneur ("source", "doc", "docs").
    if parts[0] in ("source", "doc", "docs") and len(parts) > 2:
        return f"{parts[0]}/{parts[1]}"
    return parts[0]


# --------------------------------------------------------------------------
# Adaptateurs par nature
# --------------------------------------------------------------------------

def adapt_documents(meta: dict, root: Path) -> List[DocCandidate]:
    """Nature `docs` et `code` : un fichier = un document."""
    out: List[DocCandidate] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        ext = path.suffix.lower()
        if ext not in _DOC_EXT and ext not in _CODE_EXT:
            continue
        raw = _read(path)
        if raw is None:
            continue
        text = clean_text_file(path, raw)
        min_chars = MIN_CHARS_DOC if ext in _DOC_EXT else MIN_CHARS_CODE
        if len(text) < min_chars or looks_generated(text):
            continue
        rel = path.relative_to(root)
        base_id = str(rel).replace("/", "_").replace(".", "_")
        parts = split_document(text, ext)
        for i, part in enumerate(parts, start=1):
            if len(part) < min_chars:
                continue          # queue de découpage trop maigre
            flags = {}
            suffix = ""
            if len(parts) > 1:
                flags = {"part": str(i), "n_parts": str(len(parts))}
                suffix = f"-p{i}"
            out.append(DocCandidate(
                doc_id=f"{meta['source_id']}-{base_id}{suffix}",
                source_id=meta["source_id"], family=meta["family"],
                kind=meta["kind"], rel_path=str(rel), group=_group_of(rel),
                text=part, flags=flags,
            ))
    return out


def adapt_interfaces(meta: dict, root: Path) -> List[DocCandidate]:
    """
    Nature `interfaces` : un paquet = un document.

    Les définitions sont concaténées avec leur chemin en titre, pour que le
    modèle apprenne le lien nom-qualifié -> champs (`nav2_msgs/action/
    NavigateToPose` -> goal/result/feedback).
    """
    by_package: Dict[str, List[Path]] = {}
    for path in sorted(root.rglob("*")):
        if path.is_file() and path.suffix.lower() in _INTERFACE_EXT:
            rel = path.relative_to(root)
            by_package.setdefault(rel.parts[0], []).append(path)

    out: List[DocCandidate] = []
    for package, files in sorted(by_package.items()):
        blocks = [f"# {package} — ROS 2 interface definitions", ""]
        for path in files:
            raw = _read(path)
            if raw is None or not raw.strip():
                continue
            rel = path.relative_to(root)
            kind_dir = rel.parts[1] if len(rel.parts) > 2 else ""
            qualified = f"{package}/{kind_dir}/{path.stem}" if kind_dir else \
                        f"{package}/{path.stem}"
            blocks.append(f"## {qualified} ({path.suffix.lstrip('.')})")
            blocks.append("```")
            blocks.append(raw.strip())
            blocks.append("```")
            blocks.append("")
        text = "\n".join(blocks).strip()
        if len(text) < MIN_CHARS_INTERFACE:
            continue
        out.append(DocCandidate(
            doc_id=f"{meta['source_id']}-{package}",
            source_id=meta["source_id"], family=meta["family"],
            kind=meta["kind"], rel_path=package, group=package,
            text=text, flags={"n_interfaces": str(len(files))},
        ))
    return out


def adapt_notebooks(meta: dict, root: Path) -> List[DocCandidate]:
    """
    Nature `notebooks` : cellules markdown et code, sans les sorties.

    Les sorties d'exécution (images encodées, logs) font l'essentiel du
    poids d'un .ipynb et n'apportent aucun texte utile ; les inclure
    reviendrait à polluer le corpus avec du base64.
    """
    out: List[DocCandidate] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix.lower() == ".md":
            raw = _read(path)
            if raw and len(clean_md(raw)) >= MIN_CHARS_DOC:
                rel = path.relative_to(root)
                out.append(DocCandidate(
                    doc_id=f"{meta['source_id']}-{path.stem}",
                    source_id=meta["source_id"], family=meta["family"],
                    kind=meta["kind"], rel_path=str(rel), group=_group_of(rel),
                    text=clean_md(raw),
                ))
            continue
        if path.suffix.lower() != ".ipynb":
            continue

        raw = _read(path)
        if raw is None:
            continue
        try:
            nb = json.loads(raw)
        except json.JSONDecodeError:
            continue

        blocks = [f"# {path.stem}", ""]
        for cell in nb.get("cells", []):
            src = cell.get("source", [])
            body = ("".join(src) if isinstance(src, list) else str(src)).strip()
            if not body:
                continue
            if cell.get("cell_type") == "markdown":
                blocks.append(clean_md(body))
            elif cell.get("cell_type") == "code":
                blocks.append("```python")
                blocks.append(body)
                blocks.append("```")
            blocks.append("")
        text = _BLANKS.sub("\n\n", "\n".join(blocks)).strip()
        if len(text) < MIN_CHARS_DOC:
            continue
        rel = path.relative_to(root)
        base_id = path.stem.replace(" ", "_")
        parts = split_document(text, ".md")
        for i, part in enumerate(parts, start=1):
            if len(part) < MIN_CHARS_DOC:
                continue
            flags = {"notebook": "cellules markdown+code, sorties écartées"}
            suffix = ""
            if len(parts) > 1:
                flags.update({"part": str(i), "n_parts": str(len(parts))})
                suffix = f"-p{i}"
            out.append(DocCandidate(
                doc_id=f"{meta['source_id']}-{base_id}{suffix}",
                source_id=meta["source_id"], family=meta["family"],
                kind=meta["kind"], rel_path=str(rel), group=_group_of(rel),
                text=part, flags=flags,
            ))
    return out


ADAPTERS = {
    "docs": adapt_documents,
    "code": adapt_documents,
    "interfaces": adapt_interfaces,
    "notebooks": adapt_notebooks,
}


def adapt(meta: dict, root: Path) -> List[DocCandidate]:
    adapter = ADAPTERS.get(meta["kind"])
    if adapter is None:
        raise ValueError(f"nature inconnue : {meta['kind']!r} "
                         f"(connues : {sorted(ADAPTERS)})")
    return adapter(meta, root)
