"""
Multi-provider LLM interface for phase 2, plus the numeric
anti-hallucination guardrail.

Principle: the natural-language description may be GENERATED by an LLM, but
every NUMBER comes from deterministic parsing (urdf_parser). The
`verify_numbers` guardrail checks that no number in the generated text
falls outside the set of allowed values (the extracted quantities) --
otherwise the LLM is considered to have hallucinated and the text is
rejected.

Providers are selected with the HERMES_LLM_PROVIDER environment variable
(anthropic | openai | gemini | template) or by argument. API keys are read
from the environment, never hard-coded:
  - anthropic -> ANTHROPIC_API_KEY
  - openai    -> OPENAI_API_KEY
  - gemini    -> GEMINI_API_KEY

The "template" provider makes NO network call: it produces a deterministic
template description from the extracted capabilities. It lets the whole of
phase 2 run offline / without a key (tests, CI, or simply when no LLM is
wanted at all).
"""

from __future__ import annotations

import json
import os
import re
import urllib.request
from typing import Iterable, List, Optional, Tuple


# --------------------------------------------------------------------------
# Interface
# --------------------------------------------------------------------------

class LLMProvider:
    name = "base"

    def generate(self, prompt: str, system: Optional[str] = None) -> str:
        raise NotImplementedError


# --------------------------------------------------------------------------
# Network providers (keys read from the environment). Calls go through
# urllib so no SDK is required -- if you prefer the official SDKs, replace
# the body of generate().
# --------------------------------------------------------------------------

class AnthropicProvider(LLMProvider):
    name = "anthropic"

    def __init__(self, model: str = "claude-sonnet-4-6", max_tokens: int = 1024):
        self.key = os.environ.get("ANTHROPIC_API_KEY")
        self.model, self.max_tokens = model, max_tokens

    def generate(self, prompt: str, system: Optional[str] = None) -> str:
        if not self.key:
            raise RuntimeError("ANTHROPIC_API_KEY missing from the environment.")
        body = {
            "model": self.model,
            "max_tokens": self.max_tokens,
            "messages": [{"role": "user", "content": prompt}],
        }
        if system:
            body["system"] = system
        req = urllib.request.Request(
            "https://api.anthropic.com/v1/messages",
            data=json.dumps(body).encode(),
            headers={
                "content-type": "application/json",
                "x-api-key": self.key,
                "anthropic-version": "2023-06-01",
            },
        )
        with urllib.request.urlopen(req, timeout=60) as r:
            data = json.load(r)
        return "".join(b.get("text", "") for b in data.get("content", []) if b.get("type") == "text")


class OpenAIProvider(LLMProvider):
    name = "openai"

    def __init__(self, model: str = "gpt-4o-mini", max_tokens: int = 1024):
        self.key = os.environ.get("OPENAI_API_KEY")
        self.model, self.max_tokens = model, max_tokens

    def generate(self, prompt: str, system: Optional[str] = None) -> str:
        if not self.key:
            raise RuntimeError("OPENAI_API_KEY missing from the environment.")
        messages = ([{"role": "system", "content": system}] if system else []) + \
                   [{"role": "user", "content": prompt}]
        body = {"model": self.model, "max_tokens": self.max_tokens, "messages": messages}
        req = urllib.request.Request(
            "https://api.openai.com/v1/chat/completions",
            data=json.dumps(body).encode(),
            headers={"content-type": "application/json",
                     "authorization": f"Bearer {self.key}"},
        )
        with urllib.request.urlopen(req, timeout=60) as r:
            data = json.load(r)
        return data["choices"][0]["message"]["content"]


class GeminiProvider(LLMProvider):
    name = "gemini"

    def __init__(self, model: str = "gemini-1.5-flash", max_tokens: int = 1024):
        self.key = os.environ.get("GEMINI_API_KEY")
        self.model, self.max_tokens = model, max_tokens

    def generate(self, prompt: str, system: Optional[str] = None) -> str:
        if not self.key:
            raise RuntimeError("GEMINI_API_KEY missing from the environment.")
        full = (system + "\n\n" if system else "") + prompt
        body = {"contents": [{"parts": [{"text": full}]}],
                "generationConfig": {"maxOutputTokens": self.max_tokens}}
        url = (f"https://generativelanguage.googleapis.com/v1beta/models/"
               f"{self.model}:generateContent?key={self.key}")
        req = urllib.request.Request(url, data=json.dumps(body).encode(),
                                     headers={"content-type": "application/json"})
        with urllib.request.urlopen(req, timeout=60) as r:
            data = json.load(r)
        return "".join(p.get("text", "")
                       for p in data["candidates"][0]["content"]["parts"])


# --------------------------------------------------------------------------
# "template" provider: deterministic, offline, no key.
# Used by urdf_adapter to produce a template description when no LLM is
# configured. By construction it introduces NO number that was not already
# supplied -> it always passes the guardrail.
# --------------------------------------------------------------------------

class TemplateProvider(LLMProvider):
    name = "template"

    def generate(self, prompt: str, system: Optional[str] = None) -> str:
        # The prompt is ignored: urdf_adapter calls render_template()
        # directly instead. This generate() exists only to honour the
        # interface.
        return prompt


def get_provider(name: Optional[str] = None, **kw) -> LLMProvider:
    name = (name or os.environ.get("HERMES_LLM_PROVIDER", "template")).lower()
    return {
        "anthropic": AnthropicProvider,
        "openai": OpenAIProvider,
        "gemini": GeminiProvider,
        "template": TemplateProvider,
    }.get(name, TemplateProvider)(**kw) if name != "template" else TemplateProvider()


# --------------------------------------------------------------------------
# Numeric anti-hallucination guardrail
# --------------------------------------------------------------------------

_NUM_RE = re.compile(r"-?\d+(?:[.,]\d+)?")


def extract_numbers(text: str) -> List[float]:
    out = []
    for m in _NUM_RE.findall(text):
        try:
            out.append(float(m.replace(",", ".")))
        except ValueError:
            pass
    return out


def _matches_any(value: float, allowed: Iterable[float], rel_tol: float, abs_tol: float) -> bool:
    for a in allowed:
        if abs(value - a) <= max(abs_tol, rel_tol * abs(a)):
            return True
    return False


def verify_numbers(
    generated_text: str,
    allowed_values: Iterable[float],
    *,
    rel_tol: float = 0.02,
    abs_tol: float = 0.5,
    ignore_small_ints_up_to: int = 12,
) -> Tuple[bool, List[float]]:
    """
    Check that every number in the generated text corresponds (within
    tolerance) to an allowed value (a quantity extracted from the URDF).

    - rel_tol / abs_tol: tolerance (the LLM may round 21.7 -> "22 kg").
    - ignore_small_ints_up_to: small integers (1..N) are tolerated even
      when absent from allowed_values -- they are usually turns of phrase
      ("six axes", "3 fingers") or ordinals, not physical quantities.
      Set to 0 for strict checking.

    Returns (ok, list_of_suspicious_numbers).
    """
    allowed = list(allowed_values)
    offending = []
    for v in extract_numbers(generated_text):
        if v.is_integer() and 0 <= v <= ignore_small_ints_up_to:
            continue
        if not _matches_any(v, allowed, rel_tol, abs_tol):
            offending.append(v)
    return (len(offending) == 0, offending)
