"""
Text cleaning and splitting -- shared by cat1 / cat2 / cat3.

Extracted from `cat1/text_adapters.py` when cat2 was created: both
categories collect the same formats (reStructuredText, Markdown, source
code) and had no reason to duplicate the cleaning logic.

Contains:
  - removal of Sphinx directives that carry no useful content, TOGETHER
    with their body (removing only the directive line left its options
    orphaned, `:depth: 2` floating under a heading);
  - removal of YAML front-matter, badges and HTML comments;
  - detection of auto-generated files;
  - splitting of over-long documents at their section boundaries.

None of these functions ever adds or rewords text: concatenating the parts
of a document gives back exactly the original document.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import List, Optional

# Auto-generated files: their content is repetitive and teaches nothing
# that is not better learned elsewhere.
_GENERATED_MARKERS = (
    "do not edit", "do not modify", "automatically generated",
    "autogenerated", "auto-generated", "@generated", "generated by",
)

# Maximum size of a corpus document, in characters (~7k tokens).
# Without a cap, a single file can confiscate its source's quota: the
# MuJoCo XML reference weighed 87,000 tokens, i.e. 5.7% of the whole of
# cat1 and three quarters of its source budget -- 4 MuJoCo documents kept
# instead of several dozen. An over-long document is arbitrarily re-cut at
# training time anyway: better to cut it here, at boundaries that mean
# something.
MAX_DOC_CHARS = 28_000

_RST_DROP_DIRECTIVES = {
    "toctree", "image", "figure", "only", "raw", "contents", "highlight",
    "index", "meta", "redirect-from", "include", "tab-set", "tabs",
    "youtube", "graphviz", "sectionauthor", "codeauthor",
}
_RST_DIRECTIVE_LINE = re.compile(r"^([ \t]*)\.\.[ \t]+([A-Za-z0-9_-]+)::")
_RST_ROLE = re.compile(r":[a-z:]+:`([^`]+)`")
_RST_ANCHOR = re.compile(r"^[ \t]*\.\.[ \t]+_[^:]+:[ \t]*$\n?", re.MULTILINE)
_RST_ORPHAN = re.compile(r"^[ \t]*:orphan:[ \t]*$\n?", re.MULTILINE)
_MD_FRONTMATTER = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)
_MD_BADGE = re.compile(r"^\[!\[[^\]]*\]\([^)]*\)\]\([^)]*\)[ \t]*$\n?", re.MULTILINE)
_HTML_COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)
_BLANKS = re.compile(r"\n{3,}")


def collapse_blank_lines(text: str) -> str:
    """Reduce any run of 3+ blank lines to a single separation."""
    return _BLANKS.sub("\n\n", text).strip()


def _drop_rst_directives(text: str) -> str:
    """
    Remove directives with no useful content, TOGETHER with their body.

    Removing only the directive line left its options orphaned in the
    corpus (`:depth: 2`, `:local:` floating under a heading). We therefore
    consume every line indented more deeply than the directive, which is
    exactly its scope in reStructuredText.
    """
    lines = text.split("\n")
    out: List[str] = []
    i = 0
    while i < len(lines):
        m = _RST_DIRECTIVE_LINE.match(lines[i])
        if m and m.group(2).lower() in _RST_DROP_DIRECTIVES:
            indent = len(m.group(1).expandtabs())
            i += 1
            consumed = False
            while i < len(lines):
                line = lines[i]
                if not line.strip():
                    i += 1
                    consumed = True
                    continue
                if len(line.expandtabs()) - len(line.expandtabs().lstrip()) > indent:
                    i += 1
                    consumed = True
                    continue
                break
            if consumed:
                out.append("")     # do not weld the two neighbouring paragraphs
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def clean_rst(text: str) -> str:
    text = _RST_ORPHAN.sub("", text)
    text = _RST_ANCHOR.sub("", text)
    text = _drop_rst_directives(text)
    # Sphinx roles (:doc:`this`, :class:`That`) are reduced to their label:
    # the markup teaches nothing, the word does.
    text = _RST_ROLE.sub(r"\1", text)
    return _BLANKS.sub("\n\n", text).strip()


def clean_md(text: str) -> str:
    text = _MD_FRONTMATTER.sub("", text)
    text = _HTML_COMMENT.sub("", text)
    text = _MD_BADGE.sub("", text)
    return _BLANKS.sub("\n\n", text).strip()


def clean_text_file(path: Path, text: str) -> str:
    if path.suffix.lower() == ".rst":
        return clean_rst(text)
    if path.suffix.lower() in (".md", ".markdown"):
        return clean_md(text)
    return _BLANKS.sub("\n\n", text).strip()


def looks_generated(text: str) -> bool:
    head = text[:1500].lower()
    return any(m in head for m in _GENERATED_MARKERS)


def read_text_file(path: Path) -> Optional[str]:
    try:
        return path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return None


# --------------------------------------------------------------------------
# Splitting of over-long documents
# --------------------------------------------------------------------------

# reStructuredText heading: a text line followed by an underline of the
# same character (===, ---, ~~~...).
_RST_SECTION = re.compile(r"^\S.*\n[=\-~^\"'`#*+]{3,}[ \t]*$", re.MULTILINE)
_MD_HEADING = re.compile(r"^#{1,3}[ \t]+\S.*$", re.MULTILINE)
_PY_TOPLEVEL = re.compile(r"^(?:def |class |@\w)", re.MULTILINE)
_CXX_TOPLEVEL = re.compile(r"^(?:[A-Za-z_][\w:<>,& *]*\s+)?[A-Za-z_]\w*::"
                           r"|^(?:class|struct|namespace)\s+\w", re.MULTILINE)
_PARAGRAPH = re.compile(r"\n\s*\n")


def _boundaries(text: str, ext: str):
    """Start positions of the document's natural sections."""
    if ext == ".rst":
        pattern = _RST_SECTION
    elif ext in (".md", ".markdown"):
        pattern = _MD_HEADING
    elif ext == ".py":
        pattern = _PY_TOPLEVEL
    elif ext in (".cpp", ".hpp", ".h", ".c", ".cc"):
        pattern = _CXX_TOPLEVEL
    else:
        pattern = _PARAGRAPH
    found = [m.start() for m in pattern.finditer(text)]
    if len(found) < 2:
        found = [m.start() for m in _PARAGRAPH.finditer(text)]
    return sorted({0, *found})


def _accumulate(pieces, joiner: str, max_chars: int):
    out, current = [], ""
    for piece in pieces:
        candidate = f"{current}{joiner}{piece}" if current else piece
        if len(candidate) > max_chars and current:
            out.append(current)
            current = piece
        else:
            current = candidate
    if current:
        out.append(current)
    return out


def _hard_split(segment: str, max_chars: int):
    """
    Last resort, in three tiers: paragraphs, then lines, then a raw split
    on character count.

    The last two tiers are not theoretical: Open-RMF's `reports/builds.md`
    is 281,000 characters with 4 blank lines -- a continuous-integration
    status table. Paragraph splitting alone returned it untouched, and a
    single 30,000-token document ended up in the corpus. No document may
    escape the cap.
    """
    if len(segment) <= max_chars:
        return [segment]

    parts = _accumulate(_PARAGRAPH.split(segment), "\n\n", max_chars)
    if all(len(p) <= max_chars for p in parts):
        return parts

    refined = []
    for part in parts:
        if len(part) <= max_chars:
            refined.append(part)
            continue
        by_line = _accumulate(part.split("\n"), "\n", max_chars)
        for chunk in by_line:
            if len(chunk) <= max_chars:
                refined.append(chunk)
            else:   # a single line longer than the cap
                refined.extend(chunk[i:i + max_chars]
                               for i in range(0, len(chunk), max_chars))
    return refined


def split_document(text: str, ext: str, max_chars: int = MAX_DOC_CHARS):
    """
    Split an over-long document at its section boundaries.

    No text is added or reworded: concatenating the parts gives back
    exactly the original document. The part index is carried by the
    record's metadata, not by the text.
    """
    if len(text) <= max_chars:
        return [text]

    bounds = _boundaries(text, ext)
    segments = [text[a:b] for a, b in zip(bounds, list(bounds[1:]) + [len(text)])]

    parts: List[str] = []
    current = ""
    for seg in segments:
        if len(seg) > max_chars:
            if current:
                parts.append(current)
                current = ""
            parts.extend(_hard_split(seg, max_chars))
            continue
        if len(current) + len(seg) > max_chars and current:
            parts.append(current)
            current = seg
        else:
            current += seg
    if current:
        parts.append(current)
    return [p.strip() for p in parts if p.strip()]
