"""
Nettoyage et découpage de texte -- transverse cat1 / cat2 / cat3.

Extrait de `cat1/text_adapters.py` au moment de la création de cat2 : les
deux catégories collectent les mêmes formats (reStructuredText, Markdown,
code source) et n'avaient aucune raison d'en dupliquer le nettoyage.

Contient :
  - le retrait des directives Sphinx sans contenu utile, AVEC leur corps
    (retirer la seule ligne de directive laissait ses options orphelines,
    `:depth: 2` flottant sous un titre) ;
  - le retrait du front-matter YAML, des badges et commentaires HTML ;
  - la détection des fichiers auto-générés ;
  - le découpage des documents trop longs à leurs frontières de sections.

Aucune de ces fonctions n'ajoute ni ne reformule du texte : concaténer les
parties d'un document redonne exactement le document d'origine.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import List, Optional

# Fichiers générés automatiquement : leur contenu est répétitif et
# n'apprend rien qu'on ne trouve mieux ailleurs.
_GENERATED_MARKERS = (
    "do not edit", "do not modify", "automatically generated",
    "autogenerated", "auto-generated", "@generated", "generated by",
)

# Taille maximale d'un document du corpus, en caractères (~7 k tokens).
# Sans plafond, un seul fichier peut confisquer le quota de sa source : la
# référence XML de MuJoCo pesait 87 000 tokens, soit 5,7 % de tout cat1 et
# les trois quarts du budget de sa source -- 4 documents MuJoCo retenus au
# lieu de plusieurs dizaines. Un document trop long est de toute façon
# redécoupé arbitrairement à l'entraînement : autant le couper ici, à des
# frontières qui ont un sens.
MAX_DOC_CHARS = 28_000


# --------------------------------------------------------------------------
# Nettoyage
# --------------------------------------------------------------------------

# Directives Sphinx sans contenu textuel utile : on retire la directive ET
# son corps indenté. Les directives à contenu (note, warning, code-block...)
# sont volontairement absentes de cette liste : leur texte compte.
_RST_DROP_DIRECTIVES = {
    "toctree", "image", "figure", "only", "raw", "contents", "highlight",
    "index", "meta", "redirect-from", "include", "tab-set", "tabs",
    "youtube", "graphviz", "sectionauthor", "codeauthor",
}
_RST_DIRECTIVE_LINE = re.compile(r"^([ \t]*)\.\.[ \t]+([A-Za-z0-9_-]+)::")
_RST_ROLE = re.compile(r":[a-z:]+:`([^`]+)`")
_RST_ANCHOR = re.compile(r"^[ \t]*\.\.[ \t]+_[^:]+:[ \t]*$\n?", re.MULTILINE)
_RST_ORPHAN = re.compile(r"^[ \t]*:orphan:[ \t]*$\n?", re.MULTILINE)
_MD_FRONTMATTER = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)
_MD_BADGE = re.compile(r"^\[!\[[^\]]*\]\([^)]*\)\]\([^)]*\)[ \t]*$\n?", re.MULTILINE)
_HTML_COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)
_BLANKS = re.compile(r"\n{3,}")


def collapse_blank_lines(text: str) -> str:
    """Réduit toute suite de 3 lignes vides ou plus à une seule séparation."""
    return _BLANKS.sub("\n\n", text).strip()


def _drop_rst_directives(text: str) -> str:
    """
    Retire les directives sans contenu utile AVEC leur corps.

    Un simple retrait de la ligne de directive laissait ses options
    orphelines dans le corpus (`:depth: 2`, `:local:` flottant sous un
    titre). On consomme donc toute ligne plus indentée que la directive,
    ce qui est exactement sa portée en reStructuredText.
    """
    lines = text.split("\n")
    out: List[str] = []
    i = 0
    while i < len(lines):
        m = _RST_DIRECTIVE_LINE.match(lines[i])
        if m and m.group(2).lower() in _RST_DROP_DIRECTIVES:
            indent = len(m.group(1).expandtabs())
            i += 1
            consumed = False
            while i < len(lines):
                line = lines[i]
                if not line.strip():
                    i += 1
                    consumed = True
                    continue
                if len(line.expandtabs()) - len(line.expandtabs().lstrip()) > indent:
                    i += 1
                    consumed = True
                    continue
                break
            if consumed:
                out.append("")     # ne pas souder les deux paragraphes voisins
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def clean_rst(text: str) -> str:
    text = _RST_ORPHAN.sub("", text)
    text = _RST_ANCHOR.sub("", text)
    text = _drop_rst_directives(text)
    # Les rôles Sphinx (:doc:`ceci`, :class:`Cela`) sont réduits à leur
    # libellé : le balisage n'apprend rien, le mot si.
    text = _RST_ROLE.sub(r"\1", text)
    return _BLANKS.sub("\n\n", text).strip()


def clean_md(text: str) -> str:
    text = _MD_FRONTMATTER.sub("", text)
    text = _HTML_COMMENT.sub("", text)
    text = _MD_BADGE.sub("", text)
    return _BLANKS.sub("\n\n", text).strip()


def clean_text_file(path: Path, text: str) -> str:
    if path.suffix.lower() == ".rst":
        return clean_rst(text)
    if path.suffix.lower() in (".md", ".markdown"):
        return clean_md(text)
    return _BLANKS.sub("\n\n", text).strip()


def looks_generated(text: str) -> bool:
    head = text[:1500].lower()
    return any(m in head for m in _GENERATED_MARKERS)


def read_text_file(path: Path) -> Optional[str]:
    try:
        return path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return None


# --------------------------------------------------------------------------
# Découpage des documents trop longs
# --------------------------------------------------------------------------

# Titre reStructuredText : une ligne de texte suivie d'une ligne de
# soulignement de même nature (===, ---, ~~~...).
_RST_SECTION = re.compile(r"^\S.*\n[=\-~^\"'`#*+]{3,}[ \t]*$", re.MULTILINE)
_MD_HEADING = re.compile(r"^#{1,3}[ \t]+\S.*$", re.MULTILINE)
_PY_TOPLEVEL = re.compile(r"^(?:def |class |@\w)", re.MULTILINE)
_CXX_TOPLEVEL = re.compile(r"^(?:[A-Za-z_][\w:<>,& *]*\s+)?[A-Za-z_]\w*::"
                           r"|^(?:class|struct|namespace)\s+\w", re.MULTILINE)
_PARAGRAPH = re.compile(r"\n\s*\n")


def _boundaries(text: str, ext: str):
    """Positions de début des sections naturelles du document."""
    if ext == ".rst":
        pattern = _RST_SECTION
    elif ext in (".md", ".markdown"):
        pattern = _MD_HEADING
    elif ext == ".py":
        pattern = _PY_TOPLEVEL
    elif ext in (".cpp", ".hpp", ".h", ".c", ".cc"):
        pattern = _CXX_TOPLEVEL
    else:
        pattern = _PARAGRAPH
    found = [m.start() for m in pattern.finditer(text)]
    if len(found) < 2:
        found = [m.start() for m in _PARAGRAPH.finditer(text)]
    return sorted({0, *found})


def _accumulate(pieces, joiner: str, max_chars: int):
    out, current = [], ""
    for piece in pieces:
        candidate = f"{current}{joiner}{piece}" if current else piece
        if len(candidate) > max_chars and current:
            out.append(current)
            current = piece
        else:
            current = candidate
    if current:
        out.append(current)
    return out


def _hard_split(segment: str, max_chars: int):
    """
    Dernier recours, en trois paliers : paragraphes, puis lignes, puis
    découpe brute au nombre de caractères.

    Les deux derniers paliers ne sont pas théoriques : le fichier
    `reports/builds.md` d'Open-RMF fait 281 000 caractères pour 4 lignes
    vides -- un tableau de statuts d'intégration continue. Le découpage par
    paragraphes seul le rendait tel quel, et un unique document de 30 000
    tokens ressortait dans le corpus. Aucun document ne doit pouvoir
    échapper au plafond.
    """
    if len(segment) <= max_chars:
        return [segment]

    parts = _accumulate(_PARAGRAPH.split(segment), "\n\n", max_chars)
    if all(len(p) <= max_chars for p in parts):
        return parts

    refined = []
    for part in parts:
        if len(part) <= max_chars:
            refined.append(part)
            continue
        by_line = _accumulate(part.split("\n"), "\n", max_chars)
        for chunk in by_line:
            if len(chunk) <= max_chars:
                refined.append(chunk)
            else:   # une seule ligne plus longue que le plafond
                refined.extend(chunk[i:i + max_chars]
                               for i in range(0, len(chunk), max_chars))
    return refined


def split_document(text: str, ext: str, max_chars: int = MAX_DOC_CHARS):
    """
    Découpe un document trop long à ses frontières de sections.

    Aucun texte n'est ajouté ni reformulé : les parties concaténées
    redonnent exactement le document d'origine. Le rang de la partie est
    porté par les métadonnées de l'enregistrement, pas par le texte.
    """
    if len(text) <= max_chars:
        return [text]

    bounds = _boundaries(text, ext)
    segments = [text[a:b] for a, b in zip(bounds, list(bounds[1:]) + [len(text)])]

    parts: List[str] = []
    current = ""
    for seg in segments:
        if len(seg) > max_chars:
            if current:
                parts.append(current)
                current = ""
            parts.extend(_hard_split(seg, max_chars))
            continue
        if len(current) + len(seg) > max_chars and current:
            parts.append(current)
            current = seg
        else:
            current += seg
    if current:
        parts.append(current)
    return [p.strip() for p in parts if p.strip()]

